Repository 2025-Summer-Bootcamp-team-I/I-project, pull requests merged in 2025-07, with the labels that each got.

#4 docs:리드미 테스트
  README.md
Labels: docu

#21 chore: remove __pycache__ from Git tracking
  backend/__pycache__/main.cpython-311.pyc
Labels: chore

#23 Chore/frontend base files 22
  backend/main.py
  backend/requirements.txt
  docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/AD8Page.tsx
  frontend/src/pages/ChattingSelectPage.tsx
  frontend/src/pages/DrawingPage.tsx
  frontend/src/pages/InitPage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/RegisterPage.tsx
  frontend/src/pages/ReportPage.tsx
  frontend/src/pages/TextChattingPage.tsx
  frontend/src/pages/VoiceChattingPage.tsx
  prometheus/prometheus.yml
Labels: chore

#40 Design/loading page 31
  frontend/src/index.css
  frontend/src/pages/LoadingPage.tsx
Labels: fix, design

#43 design:ad8페이지 퍼블리싱 #42
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/Background.tsx
  frontend/src/components/Header.tsx
  frontend/src/pages/AD8Page.tsx
  frontend/src/pages/InitPage.tsx
  frontend/src/store/testStore.ts
Labels: design

#46 design:ReportPage 퍼블리싱 #45
  docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/imgs/ex.png
  frontend/src/pages/AD8Page.tsx
  frontend/src/pages/ReportPage.tsx
  frontend/src/store/reportStore.ts
  frontend/src/store/testStore.ts
  frontend/src/types/html2pdf.d.ts
Labels: design

#47 design:MainPage 퍼블리싱 -33 #33
  frontend/src/components/Background.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ReportPage.tsx
Labels: design

#51 fix: 메인페이지 수정 #50
  frontend/src/pages/MainPage.tsx
Labels: fix

#67 Feat/auth 35
  backend/app/auth/api.py
  backend/app/auth/crud.py
  backend/app/auth/models.py
  backend/app/auth/schemas.py
  backend/app/auth/service.py
  backend/app/auth/utils.py
  backend/main.py
Labels: feat

#79 fix: 시계 그림 그리기 붓 굵기 조정 #77
  frontend/src/pages/DrawingPage.tsx
Labels: fix

#82 Feat/addrecord 81
  frontend/src/pages/VoiceChattingPage.tsx
Labels: feat

#85 Fix/backbuttoncolor 83
  frontend/src/pages/ChattingSelectPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/TextChattingPage.tsx
Labels: bug

#91 Fix/ad8questionbox 89
  frontend/src/pages/AD8Page.tsx
Labels: fix

#99 Fix/signuptexthover 96
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RegisterPage.tsx
Labels: bug

#101 fix: 그림그리기에서 그림 제출하면 그림 그리기 카드가 나타나도록 수정. #100
  frontend/src/pages/DrawingPage.tsx
Labels: bug

#103 fix: 보고서 페이지 육각데이터 수정 #102
  frontend/src/pages/ReportPage.tsx
Labels: bug

#98 Feat/drawing-97
  backend/app/drawing/api.py
  backend/app/drawing/crud.py
  backend/app/drawing/models.py
  backend/app/drawing/schemas.py
  backend/app/drawing/service.py
  backend/app/drawing/utils.py
  backend/main.py
  backend/requirements.txt
  backend/static/uploads/drawings/05a0d711-6b63-49f3-b4bc-258b32ae1f46.png
  backend/static/uploads/drawings/16e9060a-8fd0-42e6-8c7a-12448b87162f.png
  backend/static/uploads/drawings/388c1b1b-f1f7-4b6b-80ac-3be2606d4d4c.png
  backend/static/uploads/drawings/584ea500-b388-4073-aefa-fcb43b969f04.png
  backend/static/uploads/drawings/6e09325a-15d7-419b-bb06-f4e738777d4d.png
  backend/static/uploads/drawings/6ea75b81-e400-4fd5-b7cc-0bdfb1c977c0.png
  backend/static/uploads/drawings/b216c4ce-3c44-4525-b2f8-af0c20b1f5b3.png
  backend/static/uploads/drawings/c73d83d0-dcbd-4545-917f-796981cc38ee.png
  backend/static/uploads/drawings/f6925ebb-44d4-49c0-a7e0-60b38fb0f417.png
Labels: feat

#121 feat:드로잉 검사 페이지 연동 #120
  frontend/src/api/index.ts
  frontend/src/pages/DrawingPage.tsx
  frontend/src/types/api.ts
Labels: feat

#119 feat:AD8결과를 백엔드에 연동 #115
  frontend/src/pages/AD8Page.tsx
  frontend/src/types/api.ts
Labels: feat

#122 Feat/report-get-api #116
  .vscode/settings.json
  backend/app/database.py
  backend/app/report/models.py
  backend/app/report_view/report_view.py
  backend/main.py
Labels: bug, feat, fix

#128 Feat/TTS 기능 구현 (ElevenLabs 연동)
  backend/app/trans/tts.py
  backend/main.py
  backend/requirements.txt
Labels: chore, feat

#112 fix #110: 드로잉 서비스의 프롬프트 수정
  backend/app/drawing/api.py
  backend/app/drawing/schemas.py
  backend/app/drawing/service.py
Labels: fix

#127 Feat: 코드 리팩토링 및 기능 개선(중복 검사 금지) #126
  backend/app/database.py
  backend/app/report/api.py
  backend/app/report/crud.py
  backend/app/report/schemas.py
  backend/app/report/service.py
  frontend/src/api/index.ts
  frontend/src/pages/AD8Page.tsx
  frontend/src/pages/DrawingPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ReportPage.tsx
  frontend/src/store/reportIdStore.ts
Labels: enhancement, feat

#130 feat: Sentry 도입 및 환경변수 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.tsx
Labels: feat

#133 Feat/api 함수 추가 및 drawing test api 변경에 따른 drawing test page 변경 #131
  frontend/src/api/index.ts
  frontend/src/pages/DrawingPage.tsx
  frontend/src/types/api.ts
Labels: feat

#137 Feat/report risk indicators 132
  backend/app/ad8/api.py
  backend/app/ad8/crud.py
  backend/app/ad8/models.py
  backend/app/ad8/schemas.py
  backend/app/ad8/service.py
  backend/app/drawing/api.py
  backend/app/drawing/schemas.py
  backend/app/drawing/service.py
  backend/app/report/api.py
  backend/app/report/crud.py
  backend/app/report/models.py
  backend/app/report/schemas.py
  backend/app/report/service.py
  backend/app/report_view/report_view.py
  backend/main.py
Labels: feat

#146 Fix/백엔드 코드 변경에 따른 api 함수 수정 + 테스트 안 된 채팅 연동 코드
  backend/app/chat/api.py
  frontend/src/api/index.ts
  frontend/src/assets/imgs/robot1.png
  frontend/src/assets/imgs/robot3.png
  frontend/src/assets/imgs/robot5.png
  frontend/src/assets/imgs/robot7.png
  frontend/src/assets/imgs/robot9.png
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/TextChattingPage.tsx
  frontend/src/pages/VoiceChattingPage.tsx
  frontend/src/store/chatStore.ts
  frontend/src/types/api.ts
Labels: fix

#147 Design/reportpage 123
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/imgs/lightbulb-blue.png
  frontend/src/assets/imgs/lightbulb-red.png
  frontend/src/assets/imgs/lightbulb.png
  frontend/src/pages/ReportPage.tsx
Labels: design

#157 feat: 스트리밍 체인에 통합 프롬프트 템플릿 적용 #156
  backend/app/chat/stream_handler.py
Labels: feat

#174 chore: TTS 모델을 eleven_flash_v2_5로 변경 #173
  backend/app/trans/tts.py
Labels: chore

#181 Feat/report integration 151
  frontend/src/api/index.ts
  frontend/src/pages/ReportPage.tsx
  frontend/src/store/reportHistoryStore.ts
  frontend/src/store/reportStore.ts
Labels: feat, design

#192 Fix/채팅 보고서 오류 해결 #191
  frontend/src/api/index.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ReportPage.tsx
  frontend/src/pages/TextChattingPage.tsx
  frontend/src/pages/VoiceChattingPage.tsx
  frontend/src/store/chatStore.ts
  frontend/src/store/reportIdStore.ts
Labels: bug

#206 Design/app login,register 205
  frontend/app/src/pages/LoginPage.tsx
  frontend/app/src/pages/RegisterPage.tsx
Labels: design

#227 design/ad8페이지 디자인 수정#226
  frontend/app/src/pages/AD8Page.tsx
Labels: design

#231 Design/app init,login,register 213
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/components/AppLoginBackground.tsx
  frontend/app/src/components/AppinitBackground.tsx
  frontend/app/src/pages/InitPage.tsx
  frontend/app/src/pages/LoginPage.tsx
  frontend/app/src/pages/RegisterPage.tsx
Labels: design

#236 Feat/drawing gpt vision improve 235
  backend/app/drawing/service.py
  backend/static/uploads/drawings/시계0점-1.PNG
  backend/static/uploads/drawings/시계1점-1.PNG
  backend/static/uploads/drawings/시계1점-2.png
  backend/static/uploads/drawings/시계1점-3.png
  backend/static/uploads/drawings/시계2점-1.PNG
  backend/static/uploads/drawings/시계2점-3.PNG
  backend/static/uploads/drawings/시계3점-1.PNG
  backend/static/uploads/drawings/시계4점-1.PNG
  backend/static/uploads/drawings/시계5점-1.PNG
Labels: feat

#243 Design/app main,my,loadingpage 242
  frontend/app/src/pages/LoadingPage.tsx
  frontend/app/src/pages/MainPage.tsx
  frontend/app/src/pages/MyPage.tsx
Labels: design

#259 Chore/stream handler fix 258
  backend/app/chat/api.py
  backend/app/chat/stream_handler.py
Labels: chore, fix
